kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta4
kubernetesVersion: v1.31.0
networking:
  serviceSubnet: "10.96.0.0/16" # service用什么网段
  podSubnet: "10.244.0.0/24" # pod用什么网段
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: systemd
---
apiVersion: kubeadm.k8s.io/v1beta4
kind: InitConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock # 需要手动指定cri套接字，这是cri-dockerd默认的套接字